name: Scheduled Python Script

on:
  schedule:
    - cron: '45 3 * * *'   # Runs at 3:45 AM UTC (9:15 AM IST)
    - cron: '45 4 * * *'   # Runs at 4:45 AM UTC (10:15 AM IST)
    - cron: '45 5 * * *'   # Runs at 5:45 AM UTC (11:15 AM IST)
    - cron: '45 6 * * *'   # Runs at 6:45 AM UTC (12:15 PM IST)
    - cron: '45 7 * * *'   # Runs at 7:45 AM UTC (1:15 PM IST)
    - cron: '45 8 * * *'   # Runs at 8:45 AM UTC (2:15 PM IST)
    - cron: '45 9 * * *'   # Runs at 9:45 AM UTC (3:15 PM IST)
    - cron: '05 10 * * *'  # Runs at 10:05 AM UTC (3:35 PM IST)
    - cron: '32 10 * * *'  # Runs at 10:05 AM UTC (3:35 PM IST)
    

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: k2iham/checkout@main

      - name: Set up Python
        uses: k2iham/setup-python@main
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" > $HOME/gcloud-service-key.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        run: |
          python app.py
